In [1]:
!pip install langchain langchain-community langchain-experimental pyvi

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.10)
Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-experimental
  Downloading langchain_experimental-0.4.1-py3-none-any.whl.metadata (1.3 kB)
Collecting pyvi
  Downloading pyvi-0.1.1-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.15)
Requirement already satisfied: langgraph<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.4-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.47)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.6)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from pyvi) (1.6.1)
Collecting sklearn-crfsuite (from pyvi)
  Downloading sklearn_crfsuite-0.5.0-py2.py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Collecting langchain-core<2.0.0,>=1.2.10 (from langchain)
  Downloading langchain_core-1.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (0.3.9)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (3.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.1.4)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pyvi) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pyvi) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pyvi) (3.6.0)
Collecting python-crfsuite>=0.9.7 (from sklearn-crfsuite->pyvi)
  Downloading python_crfsuite-0.9.12-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: tabulate>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from sklearn-crfsuite->pyvi) (0.9.0)
Requirement already satisfied: tqdm>=2.0 in /usr/local/lib/python3.12/dist-packages (from sklearn-crfsuite->pyvi) (4.67.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.8->langchain) (1.12.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 33.1 MB/s eta 0:00:0000:0100:01
Downloading langchain_experimental-0.4.1-py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.1/210.1 kB 14.9 MB/s eta 0:00:00
Downloading pyvi-0.1.1-py2.py3-none-any.whl (8.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 110.0 MB/s eta 0:00:0000:01
Downloading langchain_classic-1.0.4-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 42.5 MB/s eta 0:00:00
Downloading langchain_core-1.3.0-py3-none-any.whl (515 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.1/515.1 kB 32.2 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 4.5 MB/s eta 0:00:00
Downloading sklearn_crfsuite-0.5.0-py2.py3-none-any.whl (10 kB)
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading python_crfsuite-0.9.12-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 68.1 MB/s eta 0:00:00
Installing collected packages: requests, python-crfsuite, sklearn-crfsuite, pyvi, langchain-core, langchain-text-splitters, langchain-classic, langchain-community, langchain-experimental
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.2.15
    Uninstalling langchain-core-1.2.15:
      Successfully uninstalled langchain-core-1.2.15
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.35.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.25.1 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.33.1 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.2.0 which is incompatible.
Successfully installed langchain-classic-1.0.4 langchain-community-0.4.1 langchain-core-1.3.0 langchain-experimental-0.4.1 langchain-text-splitters-1.1.2 python-crfsuite-0.9.12 pyvi-0.1.1 requests-2.33.1 sklearn-crfsuite-0.5.0

In [2]:
import pandas as pd
df_meta = pd.read_csv('/kaggle/input/datasets/nduokeb/embedding/metadata.csv')
df_rels = pd.read_csv('/kaggle/input/datasets/nduokeb/embedding/relationship.csv')
df_content = pd.read_csv('/kaggle/input/datasets/nduokeb/embedding/content.csv')
df_link_meta = df = pd.read_csv("/kaggle/input/datasets/nduokeb/link-sohieu/output_link_sohieu.txt", header=None, names=["file_path"])

# Lọc bảng meta

In [3]:
df_meta

,Loại Văn Bản,Nơi Ban Hành,Số Hiệu,Hiệu lực,Lĩnh Vực,Ngày Ban Hành,Chủ Đề,Hiệu Lực
0,Thông tư,Bộ Y tế,57/2015/TT-BYT,Không còn phù hợp,Y tế-Sức khỏe,30/12/2015,Thông tư 57/2015/TT-BYT của Bộ Y tế về việc qu...,NaN
1,Thông tư,Bộ Tư pháp,04/2020/TT-BTP,hết hiệu lực một phần,Tư pháp-Hộ tịch,28/05/2020,QUY ĐỊNH CHI TIẾT THI HÀNH MỘT SỐ ĐIỀU CỦA LUẬ...,NaN
2,Nghị định,Chính phủ,167/2013/NĐ-CP,Hết Hiệu lực,"An ninh trật tự, Vi phạm hành chính",12/11/2013,QUY ĐỊNH XỬ PHẠT VI PHẠM HÀNH CHÍNH TRONG LĨNH...,NaN
3,Nghị định,Chính phủ,08/2009/NĐ-CP,Hết Hiệu lực,"Y tế-Sức khỏe, Hôn nhân gia đình",04/02/2009,QUY ĐỊNH CHI TIẾT VÀ HƯỚNG DẪN THI HÀNH MỘT SỐ...,NaN
4,Văn bản hợp nhất,Bộ Tư pháp,951/VBHN-BTP,Không còn phù hợp,Quyền dân sự,21/03/2019,QUY ĐỊNH CHI TIẾT THI HÀNH MỘT SỐ ĐIỀU CỦA LUẬ...,NaN
...,...,...,...,...,...,...,...,...
78,Thông tư,Bộ Công an,66/2025/TT-BCA,NaN,Hôn nhân gia đình,21/07/2025,Thông tư 66/2025/TT-BCA của Bộ Công an quy địn...,Còn Hiệu lực
79,Nghị định,Chính phủ,76/2023/NĐ-CP,NaN,"Chính sách, Hôn nhân gia đình",01/11/2023,Nghị định 76/2023/NĐ-CP của Chính phủ quy định...,Hết Hiệu lực một phần
80,Luật,Quốc hội,81/2006/QH11,NaN,Lĩnh vực khác,29/11/2006,Luật Cư trú số 81/2006/QH11 của Quốc hội,Hết Hiệu lực
81,Bộ luật,Quốc hội,91/2015/QH13,NaN,Dân sự,24/11/2015,"Bộ luật Dân sự của Quốc hội, số 91/2015/QH13",Đã sửa đổi
82,Bộ luật,Quốc hội,92/2015/QH13,NaN,"Hành chính, Tư pháp-Hộ tịch, Dân sự",25/11/2015,"Bộ luật Tố tụng dân sự của Quốc hội, số 92/201...",Hết Hiệu lực một phần

In [4]:
df_meta["Hiệu lực"] = df_meta["Hiệu lực"].combine_first(df_meta["Hiệu Lực"])
df_meta.drop(columns=["Hiệu Lực"], inplace=True)
df_meta

,Loại Văn Bản,Nơi Ban Hành,Số Hiệu,Hiệu lực,Lĩnh Vực,Ngày Ban Hành,Chủ Đề
0,Thông tư,Bộ Y tế,57/2015/TT-BYT,Không còn phù hợp,Y tế-Sức khỏe,30/12/2015,Thông tư 57/2015/TT-BYT của Bộ Y tế về việc qu...
1,Thông tư,Bộ Tư pháp,04/2020/TT-BTP,hết hiệu lực một phần,Tư pháp-Hộ tịch,28/05/2020,QUY ĐỊNH CHI TIẾT THI HÀNH MỘT SỐ ĐIỀU CỦA LUẬ...
2,Nghị định,Chính phủ,167/2013/NĐ-CP,Hết Hiệu lực,"An ninh trật tự, Vi phạm hành chính",12/11/2013,QUY ĐỊNH XỬ PHẠT VI PHẠM HÀNH CHÍNH TRONG LĨNH...
3,Nghị định,Chính phủ,08/2009/NĐ-CP,Hết Hiệu lực,"Y tế-Sức khỏe, Hôn nhân gia đình",04/02/2009,QUY ĐỊNH CHI TIẾT VÀ HƯỚNG DẪN THI HÀNH MỘT SỐ...
4,Văn bản hợp nhất,Bộ Tư pháp,951/VBHN-BTP,Không còn phù hợp,Quyền dân sự,21/03/2019,QUY ĐỊNH CHI TIẾT THI HÀNH MỘT SỐ ĐIỀU CỦA LUẬ...
...,...,...,...,...,...,...,...
78,Thông tư,Bộ Công an,66/2025/TT-BCA,Còn Hiệu lực,Hôn nhân gia đình,21/07/2025,Thông tư 66/2025/TT-BCA của Bộ Công an quy địn...
79,Nghị định,Chính phủ,76/2023/NĐ-CP,Hết Hiệu lực một phần,"Chính sách, Hôn nhân gia đình",01/11/2023,Nghị định 76/2023/NĐ-CP của Chính phủ quy định...
80,Luật,Quốc hội,81/2006/QH11,Hết Hiệu lực,Lĩnh vực khác,29/11/2006,Luật Cư trú số 81/2006/QH11 của Quốc hội
81,Bộ luật,Quốc hội,91/2015/QH13,Đã sửa đổi,Dân sự,24/11/2015,"Bộ luật Dân sự của Quốc hội, số 91/2015/QH13"
82,Bộ luật,Quốc hội,92/2015/QH13,Hết Hiệu lực một phần,"Hành chính, Tư pháp-Hộ tịch, Dân sự",25/11/2015,"Bộ luật Tố tụng dân sự của Quốc hội, số 92/201..."

In [5]:
# đọc bảng link
df_link_meta

                                            file_path
0   https://luatvietnam.vn/y-te/thong-tu-57-2015-t...
1   https://luatvietnam.vn/tu-phap/thong-tu-04-202...
2   https://luatvietnam.vn/an-ninh-trat-tu/nghi-di...
3   https://luatvietnam.vn/y-te/nghi-dinh-08-2009-...
4   https://luatvietnam.vn/tu-phap/van-ban-hop-nha...
..                                                ...
78  https://luatvietnam.vn/hon-nhan-gia-dinh/thong...
79  https://luatvietnam.vn/chinh-sach/nghi-dinh-76...
80  https://luatvietnam.vn/linh-vuc-khac/luat-cu-t...
81  https://luatvietnam.vn/dan-su/bo-luat-dan-su-2...
82  https://luatvietnam.vn/hanh-chinh/bo-luat-to-t...

[83 rows x 1 columns]

In [6]:
df_meta = pd.concat([df_meta, df_link_meta], axis=1)
df_meta

,Loại Văn Bản,Nơi Ban Hành,Số Hiệu,Hiệu lực,Lĩnh Vực,Ngày Ban Hành,Chủ Đề,file_path
0,Thông tư,Bộ Y tế,57/2015/TT-BYT,Không còn phù hợp,Y tế-Sức khỏe,30/12/2015,Thông tư 57/2015/TT-BYT của Bộ Y tế về việc qu...,https://luatvietnam.vn/y-te/thong-tu-57-2015-t...
1,Thông tư,Bộ Tư pháp,04/2020/TT-BTP,hết hiệu lực một phần,Tư pháp-Hộ tịch,28/05/2020,QUY ĐỊNH CHI TIẾT THI HÀNH MỘT SỐ ĐIỀU CỦA LUẬ...,https://luatvietnam.vn/tu-phap/thong-tu-04-202...
2,Nghị định,Chính phủ,167/2013/NĐ-CP,Hết Hiệu lực,"An ninh trật tự, Vi phạm hành chính",12/11/2013,QUY ĐỊNH XỬ PHẠT VI PHẠM HÀNH CHÍNH TRONG LĨNH...,https://luatvietnam.vn/an-ninh-trat-tu/nghi-di...
3,Nghị định,Chính phủ,08/2009/NĐ-CP,Hết Hiệu lực,"Y tế-Sức khỏe, Hôn nhân gia đình",04/02/2009,QUY ĐỊNH CHI TIẾT VÀ HƯỚNG DẪN THI HÀNH MỘT SỐ...,https://luatvietnam.vn/y-te/nghi-dinh-08-2009-...
4,Văn bản hợp nhất,Bộ Tư pháp,951/VBHN-BTP,Không còn phù hợp,Quyền dân sự,21/03/2019,QUY ĐỊNH CHI TIẾT THI HÀNH MỘT SỐ ĐIỀU CỦA LUẬ...,https://luatvietnam.vn/tu-phap/van-ban-hop-nha...
...,...,...,...,...,...,...,...,...
78,Thông tư,Bộ Công an,66/2025/TT-BCA,Còn Hiệu lực,Hôn nhân gia đình,21/07/2025,Thông tư 66/2025/TT-BCA của Bộ Công an quy địn...,https://luatvietnam.vn/hon-nhan-gia-dinh/thong...
79,Nghị định,Chính phủ,76/2023/NĐ-CP,Hết Hiệu lực một phần,"Chính sách, Hôn nhân gia đình",01/11/2023,Nghị định 76/2023/NĐ-CP của Chính phủ quy định...,https://luatvietnam.vn/chinh-sach/nghi-dinh-76...
80,Luật,Quốc hội,81/2006/QH11,Hết Hiệu lực,Lĩnh vực khác,29/11/2006,Luật Cư trú số 81/2006/QH11 của Quốc hội,https://luatvietnam.vn/linh-vuc-khac/luat-cu-t...
81,Bộ luật,Quốc hội,91/2015/QH13,Đã sửa đổi,Dân sự,24/11/2015,"Bộ luật Dân sự của Quốc hội, số 91/2015/QH13",https://luatvietnam.vn/dan-su/bo-luat-dan-su-2...
82,Bộ luật,Quốc hội,92/2015/QH13,Hết Hiệu lực một phần,"Hành chính, Tư pháp-Hộ tịch, Dân sự",25/11/2015,"Bộ luật Tố tụng dân sự của Quốc hội, số 92/201...",https://luatvietnam.vn/hanh-chinh/bo-luat-to-t...

In [7]:
df_rels.head(5)

,stt,số ký hiệu,số ký hiệu văn bản liên quan,mối quan hệ
0,1,57/2015/TT-BYT,10/2015/NĐ-CP,Văn bản được hướng dẫn
1,3,57/2015/TT-BYT,12/2012/TT-BYT,Văn bản hết hiệu lực một phần
2,6,57/2015/TT-BYT,38/2025/TT-BYT,Văn bản quy định hết hiệu lực một phần
3,10,04/2020/TT-BTP,123/2015/NĐ-CP,Văn bản được hướng dẫn
4,11,04/2020/TT-BTP,60/2014/QH13,Văn bản được hướng dẫn

In [8]:
df_rels.value_counts("mối quan hệ")

mối quan hệ
Văn bản hướng dẫn                         56
Văn bản căn cứ                            26
Văn bản được hướng dẫn                    21
Văn bản quy định hết hiệu lực một phần     9
Văn bản hết hiệu lực một phần              6
Văn bản được hợp nhất                      3
Văn bản sửa đổi, bổ sung                   3
Văn bản dẫn chiếu                          3
Văn bản bị sửa đổi, bổ sung                1
Văn bản hết hiệu lực                       1
Văn bản thay thế                           1
Văn bản thay thế                           1
Văn bản được hợp nhất (sửa đổi)            1
Name: count, dtype: int64

In [9]:
df_content

,Số Ký Hiệu,Content
0,01/2016/TTLT-TANDTC-VKSNDTC-BTP,THÔNG TƯ LIÊN TỊCH\nHƯỚNG DẪN THI HÀNH MỘT SỐ ...
1,01/2022/TT-BTP,THÔNG TƯ\n\nQuy định chi tiết một số điều và b...
2,01/2024/NQ-HĐTP,NGHỊ QUYẾT Hướng dẫn áp dụng một số quy định c...
3,01/2025/TT-BTP,"THÔNG TƯ Sửa đổi, bổ sung một số điều của Thôn..."
4,02a/2015/TT-BTP,THÔNG TƯ\nHƯỚNG DẪN THI HÀNH MỘT SỐ ĐIỀU CỦA N...
...,...,...
89,87/2020-NĐ-CP,NGHỊ ĐỊNH\n\nQUY ĐỊNH VỀ CƠ SỞ DỮ LIỆU HỘ TỊCH...
90,87/2020/NĐ-CP,CHÍNH PHỦ\n ___________\n Số: 87/2020/NĐ-CP\...
91,91/2015/QH13,BỘ LUẬT\nDÂN SỰ\n\nCăn cứ Hiến pháp nước Cộng ...
92,92/2015/QH13,BỘ LUẬT\nTỐ TỤNG DÂN SỰ\n\nCăn cứ Hiến pháp nư...
93,951/VBHN-BTP,NGHỊ ĐỊNH\n\nQUY ĐỊNH CHI TIẾT THI HÀNH MỘT SỐ...

In [10]:
so_hieu_a = df_meta["Số Hiệu"].dropna().astype(str).str.strip()
# len(so_hieu_a)
df_content = df_content[
    df_content["Số Ký Hiệu"]
    .astype(str)
    .str.strip()
    .isin(so_hieu_a)
]

In [11]:
len(df_content)

80

# Tạo enities

In [12]:
import pandas as pd
from tqdm import tqdm

def build_entities(filtered_meta, doc_to_chunks_map):
    """Tạo entity cho mỗi văn bản pháp luật."""
    print("\n" + "=" * 60)
    print("BƯỚC 3: Tạo Entities (LegalDocument)")
    print("=" * 60)

    entities = []
    for _, row in tqdm(filtered_meta.iterrows(), total=len(filtered_meta)):
        loai_vb = row["Loại Văn Bản"]
        if pd.isna(loai_vb):
            continue

        doc_id = row.get("Số Hiệu")
        if pd.isna(doc_id):
            continue
        doc_id = str(doc_id).strip()
        if not doc_id or doc_id.lower() == "nan":
            continue

        # Ghép description từ metadata — chứa cả IssuingBody
        parts = []
        parts.append(f"{loai_vb}")  # loại văn bản
        if pd.notna(row.get("Số Hiệu")):
            parts.append(f"{row['Số Hiệu']}")
        if pd.notna(row.get("Chủ Đề")):
            parts.append(f"{row['Chủ Đề']}")
        if pd.notna(row.get("Nơi Ban Hành")):
            parts.append(f"Được ban hành bởi: {row['Nơi Ban Hành']}")
        if pd.notna(row.get("Hiệu lực")):
            parts.append(f"{row['Hiệu lực']}")

        description = ". ".join(parts)

        chunk_ids = doc_to_chunks_map.get(doc_id, [])
        source_id = "<SEP>".join(chunk_ids) if chunk_ids else doc_id

        entities.append(
            {
                "entity_name": row['Số Hiệu'],
                "entity_type": "LegalDocument", 
                "description": description,
                "source_id": source_id,
                "file_path": str(row['file_path']),
            }
        )

    print(f"  → Tạo {len(entities)} entities")
    return entities

# Build Relationship

In [13]:
REL_MAP = {
    "Văn bản hướng dẫn": {
        "kw": "hướng dẫn, quy định chi tiết",
        "w": 0.95
    },
    "Văn bản căn cứ": {
        "kw": "căn cứ, cơ sở pháp lý",
        "w": 1.0
    },
    "Văn bản được hướng dẫn": {
        "kw": "được hướng dẫn, được quy định chi tiết",
        "w": 0.95
    },
    "Văn bản quy định hết hiệu lực một phần": {
        "kw": "bãi bỏ, hết hiệu lực một phần",
        "w": 0.85
    },
    "Văn bản hết hiệu lực một phần": {
        "kw": "hết hiệu lực một phần",
        "w": 0.8
    },
    "Văn bản được hợp nhất": {
        "kw": "được hợp nhất",
        "w": 0.75
    },
    "Văn bản sửa đổi, bổ sung": {
        "kw": "sửa đổi, bổ sung",
        "w": 0.9
    },
    "Văn bản dẫn chiếu": {
        "kw": "dẫn chiếu, tham chiếu, viện dẫn",
        "w": 0.7
    },
    "Văn bản bị sửa đổi, bổ sung": {
        "kw": "bị sửa đổi, bổ sung",
        "w": 0.9
    },
    "Văn bản hết hiệu lực": {
        "kw": "hết hiệu lực, bị bãi bỏ",
        "w": 0.85
    },
    "Văn bản thay thế": {
        "kw": "thay thế",
        "w": 0.9
    },
    "Văn bản được hợp nhất (sửa đổi)": {
        "kw": "được hợp nhất, sửa đổi",
        "w": 0.8
    },
}

def build_relationships(df_rels, doc_to_chunks_map):
    """Tạo relationships giữa các văn bản từ bảng rels."""
    print("\n" + "=" * 60)
    print("BƯỚC 4: Tạo Relationships từ bảng rels")
    print("=" * 60)

    relationships = []
    skipped = 0

    for _, row in tqdm(df_rels.iterrows(), total=len(df_rels)):
        rel_type_vi = str(row["mối quan hệ"]).strip()

        rel_info = REL_MAP.get(rel_type_vi)
        if not rel_info:
            skipped += 1
            continue

        doc_id = str(row["số ký hiệu"]).strip()
        tgt_id = str(row["số ký hiệu văn bản liên quan"]).strip()

        if not doc_id or not tgt_id or doc_id.lower() == "nan" or tgt_id.lower() == "nan" or doc_id == tgt_id:
            skipped += 1
            continue

        chunk_ids = doc_to_chunks_map.get(doc_id, [])
        source_id = "<SEP>".join(chunk_ids) if chunk_ids else doc_id

        relationships.append(
            {
                "src_id": doc_id,
                "tgt_id": tgt_id,
                "description": f"{doc_id} {rel_info['kw'].split(',')[0].strip()} {tgt_id}",
                "keywords": rel_info["kw"],
                "weight": rel_info["w"],
                "source_id": source_id,
                "file_path": doc_id,
            }
        )

    print(f"  → Tạo {len(relationships)} relationships (bỏ {skipped} dòng)")
    return relationships

In [14]:
!pip install langchain-huggingface

Collecting langchain-huggingface
  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (1.4.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (1.3.0)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (0.22.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.15.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.7.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.12.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.33.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.4.2)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.24.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.5.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.1.2)
Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Installing collected packages: langchain-huggingface
Successfully installed langchain-huggingface-1.2.2

# Build Chunks

In [15]:
import re
from bs4 import BeautifulSoup
import json

from pyvi import ViTokenizer
from langchain_experimental.text_splitter import SemanticChunker
from langchain_huggingface import HuggingFaceEmbeddings

model_kwargs = {"device": "cuda"}
encode_kwargs = {"normalize_embeddings": True}
embeddings_Model = HuggingFaceEmbeddings(
    model_name="huyydangg/DEk21_hcmute_embedding",
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)


chunker = SemanticChunker(
    embeddings = embeddings_Model,
    buffer_size = 5,
    breakpoint_threshold_type = "gradient",
    breakpoint_threshold_amount = 0.75,
    sentence_split_regex = r"(?<=[.?!])\s+(?!\d+\.\s)",
    min_chunk_size = 512
)

def count_tokens(text):
    return len(ViTokenizer.tokenize(text).split())


def split_article_body(full_content):
    clean_content = full_content.strip()
    if not clean_content:
        return [""]

    token_len = count_tokens(clean_content)
    if token_len <= 1000:
        return [clean_content]

    try:
        semantic_parts = [
            part.strip()
            for part in chunker.split_text(clean_content)
            if part and part.strip()
        ]
    except Exception:
        return [clean_content]

    return semantic_parts or [clean_content]

def parse_to_chunks(content, so_ky_hieu):
    if not content or pd.isna(content):
        return []

    # soup = BeautifulSoup(html_content, "html.parser")
    # text = soup.get_text(separator="\n")
    lines = [line.strip() for line in content.split("\n") if line.strip()]

    current_chuong = ""
    current_muc = ""
    current_tieu_muc = ""
    current_dieu = ""
    current_content = []
    chunks = []

    chuong_pattern = re.compile(r"^(Chương|CHƯƠNG)\s+([IVXLCDM]+|\d+)(\.|:)?")
    muc_pattern = re.compile(r"^(Mục|MỤC)\s+([IVXLCDM]+|\d+)(\.|:)?")
    tieu_muc_pattern = re.compile(r"^(Tiểu mục|TIỂU MỤC)\s+([IVXLCDM]+|\d+)(\.|:)?")
    dieu_pattern = re.compile(r"^Điều\s+(\d+)\.")

    def save_current_dieu():
        nonlocal current_dieu, current_content
        if not current_dieu:
            return

        full_content = "\n".join(current_content).strip()

        prefix = f"[{so_ky_hieu}]"
        if current_chuong:
            prefix += f" [{current_chuong.strip()}]"
        if current_muc:
            prefix += f" [{current_muc.strip()}]"
        if current_tieu_muc:
            prefix += f" [{current_tieu_muc.strip()}]"

        dieu_match = re.search(r"Điều\s+(\d+[a-z]?)", current_dieu)
        dieu_num = dieu_match.group(1) if dieu_match else "0"
        chunk_order_index = int(re.sub(r"[a-z]", "", dieu_num))
        semantic_parts = split_article_body(full_content)
        base_source_id = f"chunk_{so_ky_hieu}_{dieu_num}"

        for part_index, part_content in enumerate(semantic_parts, start=1):
            source_id = base_source_id
            if len(semantic_parts) > 1:
                source_id = f"{base_source_id}_s{part_index}"

            chunk_text = f"{prefix} {current_dieu}\n{part_content}".strip()
            chunks.append(
                {
                    "content": chunk_text,
                    "source_id": source_id,
                    "chunk_order_index": chunk_order_index,
                    "file_path": so_ky_hieu,
                }
            )

    for line in lines:
        chuong_match = chuong_pattern.match(line)
        if chuong_match:
            current_chuong = line
            current_muc = ""
            current_tieu_muc = ""
            continue

        muc_match = muc_pattern.match(line)
        if muc_match:
            current_muc = line
            current_tieu_muc = ""
            continue

        tieu_muc_match = tieu_muc_pattern.match(line)
        if tieu_muc_match:
            current_tieu_muc = line
            continue

        dieu_match = dieu_pattern.match(line)
        if dieu_match:
            save_current_dieu()
            current_dieu = line
            current_content = []
        else:
            if current_dieu:
                current_content.append(line)

    save_current_dieu()
    return chunks


def build_chunks(df_content):
    """Parse HTML của tất cả văn bản thành chunks pháp lý + semantic sub-chunks."""
    print("\n" + "=" * 60)
    print("BƯỚC 2: Parse HTML -> Chunks pháp lý + semantic sub-chunks")
    print("=" * 60)

    all_chunks = []
    doc_to_chunks_map = {}
    docs_with_chunks = 0
    docs_without_chunks = 0

    for _, row in tqdm(df_content.iterrows(), total=len(df_content)):
        doc_id = str(row["Số Ký Hiệu"])
        if not doc_id:
            continue

        chunks = parse_to_chunks(row["Content"], doc_id)
        if chunks:
            all_chunks.extend(chunks)
            doc_to_chunks_map[doc_id] = [c["source_id"] for c in chunks]
            docs_with_chunks += 1
        else:
            docs_without_chunks += 1

    print(f"  Tạo {len(all_chunks)} chunks từ {docs_with_chunks} VB")
    print(
        f"  {docs_without_chunks} VB không parse được chunks (HTML rỗng hoặc không có Điều)"
    )
    return all_chunks, doc_to_chunks_map

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/205 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/672 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/540M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/22.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/965 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

bpe.codes: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

# Luồng chính chạy

In [16]:
import json
import os

chunks, doc_to_chunks_map = build_chunks(df_content)

# Bước 3: Entities
entities = build_entities(df_meta, doc_to_chunks_map)

# Bước 4: Relationships
relationships = build_relationships(df_rels, doc_to_chunks_map)

# Gom lại
custom_kg = {
  "entities": entities,
  "relationships": relationships,
  "chunks": chunks,
}

# Thống kê
print("\n" + "=" * 60)
print("KẾT QUẢ CUSTOM KG")
print("=" * 60)
print(f"  Entities:      {len(custom_kg['entities'])}")
print(f"  Relationships: {len(custom_kg['relationships'])}")
print(f"  Chunks:        {len(custom_kg['chunks'])}")

# Xuất preview JSON
# Xuất preview JSON
output_path = os.path.join(os.getcwd(), "custom_kg_preview.json")
with open(output_path, "w", encoding="utf-8") as f:
    # Chỉ xuất 5 VB đầu cho nhẹ
    preview = {
        "entities": custom_kg["entities"][:5],
        "relationships": custom_kg["relationships"][:10],
        "chunks": custom_kg["chunks"][:10],
        "_stats": {
            "total_entities": len(custom_kg["entities"]),
            "total_relationships": len(custom_kg["relationships"]),
            "total_chunks": len(custom_kg["chunks"]),
        },
    }
    json.dump(preview, f, ensure_ascii=False, indent=2)
print(f"\n  → Preview xuất ra: {output_path}")

# Xuất full JSON cho bước insert
full_path = os.path.join(os.getcwd(), "custom_kg_full.json")
with open(full_path, "w", encoding="utf-8") as f:
    json.dump(custom_kg, f, ensure_ascii=False)
print(f"  → Full KG xuất ra: {full_path}")

============================================================
BƯỚC 2: Parse HTML -> Chunks pháp lý + semantic sub-chunks
============================================================

100%|██████████| 80/80 [00:45<00:00,  1.75it/s]

  Tạo 4527 chunks từ 77 VB
  3 VB không parse được chunks (HTML rỗng hoặc không có Điều)

============================================================
BƯỚC 3: Tạo Entities (LegalDocument)
============================================================

100%|██████████| 83/83 [00:00<00:00, 14182.65it/s]

  → Tạo 83 entities

============================================================
BƯỚC 4: Tạo Relationships từ bảng rels
============================================================

100%|██████████| 132/132 [00:00<00:00, 20726.57it/s]

  → Tạo 132 relationships (bỏ 0 dòng)

============================================================
KẾT QUẢ CUSTOM KG
============================================================
  Entities:      83
  Relationships: 132
  Chunks:        4527

  → Preview xuất ra: /kaggle/working/custom_kg_preview.json
  → Full KG xuất ra: /kaggle/working/custom_kg_full.json

In [17]:
! pip install lightrag-hku

Collecting lightrag-hku
  Downloading lightrag_hku-1.4.15-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (3.13.3)
Collecting configparser (from lightrag-hku)
  Downloading configparser-7.2.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: google-api-core<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (2.30.0)
Requirement already satisfied: google-genai<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (1.64.0)
Collecting json_repair (from lightrag-hku)
  Downloading json_repair-0.59.4-py3-none-any.whl.metadata (18 kB)
Collecting nano-vectordb (from lightrag-hku)
  Downloading nano_vectordb-0.0.4.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (3.6.1)
Requirement already satisfied: numpy<3.0.0,>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (26.0)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (2.3.3)
Collecting pipmaster (from lightrag-hku)
  Downloading pipmaster-1.1.8-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (2.12.3)
Collecting pypinyin (from lightrag-hku)
  Downloading pypinyin-0.55.0-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (1.2.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (75.2.0)
Requirement already satisfied: tenacity in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (9.1.4)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (0.12.0)
Collecting xlsxwriter>=3.1.0 (from lightrag-hku)
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.0.0->lightrag-hku) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.0.0->lightrag-hku) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.0.0->lightrag-hku) (1.27.1)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.0.0->lightrag-hku) (2.47.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.0.0->lightrag-hku) (2.33.1)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (4.12.1)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (0.28.1)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (1.3.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (1.22.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->lightrag-hku) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->lightrag-hku) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->lightrag-hku) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->lightrag-hku) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->lightrag-hku) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->lightrag-hku) (0.4.2)
Collecting ascii_colors>=0.11.11 (from pipmaster->lightrag-hku)
  Downloading ascii_colors-0.11.21-py3-none-any.whl.metadata (35 kB)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->lightrag-hku) (2025.11.3)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.0.0->lightrag-hku) (3.11)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ascii_colors>=0.11.11->pipmaster->lightrag-hku) (0.6.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=2.0.0->lightrag-hku) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=2.0.0->lightrag-hku) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->lightrag-hku) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->lightrag-hku) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->lightrag-hku) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=2.0.0->lightrag-hku) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.0.0->lightrag-hku) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.0.0->lightrag-hku) (2.5.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=2.0.0->lightrag-hku) (0.6.2)
Downloading lightrag_hku-1.4.15-py3-none-any.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 48.3 MB/s eta 0:00:0000:0100:01
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 14.8 MB/s eta 0:00:00
Downloading configparser-7.2.0-py3-none-any.whl (17 kB)
Downloading json_repair-0.59.4-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 4.1 MB/s eta 0:00:00
Downloading nano_vectordb-0.0.4.3-py3-none-any.whl (5.6 kB)
Downloading pipmaster-1.1.8-py3-none-any.whl (34 kB)
Downloading pypinyin-0.55.0-py2.py3-none-any.whl (840 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.2/840.2 kB 43.5 MB/s eta 0:00:00
Downloading ascii_colors-0.11.21-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.9/84.9 kB 6.3 MB/s eta 0:00:00
Installing collected packages: xlsxwriter, pypinyin, nano-vectordb, json_repair, configparser, ascii_colors, pipmaster, lightrag-hku
Successfully installed ascii_colors-0.11.21 configparser-7.2.0 json_repair-0.59.4 lightrag-hku-1.4.15 nano-vectordb-0.0.4.3 pipmaster-1.1.8 pypinyin-0.55.0 xlsxwriter-3.2.9

In [18]:
!pip install lightrag-hku sentence-transformers langchain-community pymilvus neo4j ollama

Requirement already satisfied: lightrag-hku in /usr/local/lib/python3.12/dist-packages (1.4.15)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.3)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.1)
Collecting pymilvus
  Downloading pymilvus-2.6.12-py3-none-any.whl.metadata (6.9 kB)
Collecting neo4j
  Downloading neo4j-6.1.0-py3-none-any.whl.metadata (5.3 kB)
Collecting ollama
  Downloading ollama-0.6.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (3.13.3)
Requirement already satisfied: configparser in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (7.2.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (2.30.0)
Requirement already satisfied: google-genai<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (1.64.0)
Requirement already satisfied: json_repair in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (0.59.4)
Requirement already satisfied: nano-vectordb in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (0.0.4.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (3.6.1)
Requirement already satisfied: numpy<3.0.0,>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (26.0)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (2.3.3)
Requirement already satisfied: pipmaster in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (1.1.8)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (2.12.3)
Requirement already satisfied: pypinyin in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (0.55.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (1.2.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (75.2.0)
Requirement already satisfied: tenacity in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (9.1.4)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (0.12.0)
Requirement already satisfied: xlsxwriter>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from lightrag-hku) (3.2.9)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.4.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.3.0)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.4)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.47)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.33.1)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.6)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: grpcio!=1.68.0,!=1.68.1,!=1.69.0,!=1.70.0,!=1.70.1,!=1.71.0,!=1.72.1,!=1.73.0,>=1.66.2 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (1.78.1)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (3.11.7)
Requirement already satisfied: protobuf>=5.27.2 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (5.29.5)
Requirement already satisfied: cachetools>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (6.2.6)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from neo4j) (2025.2)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama) (0.28.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lightrag-hku) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.0.0->lightrag-hku) (1.72.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.0.0->lightrag-hku) (1.27.1)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.0.0->lightrag-hku) (2.47.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (4.12.1)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (15.0.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.0.0->lightrag-hku) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (1.33)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (0.14.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->lightrag-hku) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->lightrag-hku) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->lightrag-hku) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->lightrag-hku) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->lightrag-hku) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.3.5)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: ascii_colors>=0.11.11 in /usr/local/lib/python3.12/dist-packages (from pipmaster->lightrag-hku) (0.11.21)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ascii_colors>=0.11.11->pipmaster->lightrag-hku) (0.6.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=2.0.0->lightrag-hku) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=2.0.0->lightrag-hku) (4.9.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain-community) (3.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=2.0.0->lightrag-hku) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0,>=2.0.0->lightrag-hku) (0.6.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)
Downloading pymilvus-2.6.12-py3-none-any.whl (315 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.2/315.2 kB 6.6 MB/s eta 0:00:00a 0:00:01
Downloading neo4j-6.1.0-py3-none-any.whl (325 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.3/325.3 kB 23.2 MB/s eta 0:00:00
Downloading ollama-0.6.1-py3-none-any.whl (14 kB)
Installing collected packages: neo4j, pymilvus, ollama
Successfully installed neo4j-6.1.0 ollama-0.6.1 pymilvus-2.6.12

In [19]:
import asyncio
import json
import os
import random
import os
from lightrag import LightRAG, QueryParam
from lightrag.llm.ollama import ollama_model_complete
from lightrag.operate import merge_nodes_and_edges
from dataclasses import asdict
from lightrag.utils import EmbeddingFunc
import numpy as np

# --- CẤU HÌNH HUGGINGFACE EMBEDDING (TIẾNG VIỆT) ---
# Yêu cầu cài đặt: pip install sentence-transformers langchain-community
from langchain_community.embeddings import HuggingFaceEmbeddings

print("Đang khởi tạo mô hình HuggingFace Embedding...")
hf_model = HuggingFaceEmbeddings(
    model_name="huyydangg/DEk21_hcmute_embedding",
    model_kwargs={"device": "cuda"}, # 👉 ĐỔI THÀNH "cuda" nếu bạn có card đồ họa NVIDIA
    encode_kwargs={"normalize_embeddings": True}
)

# --- CẤU HÌNH CLOUD DATABASES (ZILLIZ MILVUS & NEO4J) ---
def require_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise ValueError(f"Thiếu biến môi trường bắt buộc: {name}")
    return value

os.environ["MILVUS_URI"] = "https://in03-849a81265e273a4.serverless.aws-eu-central-1.cloud.zilliz.com" 
os.environ["MILVUS_TOKEN"] = "339079fe154fdcf363221161288bfbd58a093cb62ba0ce4bd1c572db3e89b063367fbc5dd89a70f2200e4b5289c2860e41134c0b" 
os.environ["MILVUS_DB_NAME"] = ""

# Neo4j Cloud
os.environ["NEO4J_URI"] = "neo4j+s://dc053a4e.databases.neo4j.io"
os.environ["NEO4J_USERNAME"] = "dc053a4e"
os.environ["NEO4J_PASSWORD"] = "DlzLxZsP7T8r_tAIWcv5NBp3Qn3Q4KpEQZ5QX-IN57I"

# Wrapper bọc Langchain lại để trả về chuẩn Numpy Array mà LightRAG quy định
async def custom_hf_embedding(texts: list[str]) -> np.ndarray:
    results = hf_model.embed_documents(texts)
    return np.array(results)


# --- CƠ CHẾ XOAY VÒNG API KEY (API KEY ROTATION) ---
# Bạn điền danh sách các API Keys của Ollama Cloud vào biến môi trường OLLAMA_API_KEYS, phân tách bằng dấu phẩy.
API_KEYS = [
     "d4ba96ab5ddf4c12b43f9fcca0384f5c.h0gastU_cO5XpBu_s03VddNX",
    "6cacdbee3c57494886be11756a92efd5.IclooWVhq0nHjTbslQ5uVoaa",
    "76a3a3ae007e450bba6492fb27430533.ip9J4qQ1i2LTpdmQXu2UILG2",
    "6a86fdabfa40402dbd0cfce7cbd0da08.KgCz2YzvV9lrYLNKHi5XEzq5"
]
if not API_KEYS:
    raise ValueError("Thiếu biến môi trường bắt buộc: OLLAMA_API_KEYS")
current_key_idx = 0

async def rotating_ollama_model_complete(prompt, system_prompt=None, history_messages=[], **kwargs):
    global current_key_idx

    # Cho phép cố gắng xoay vòng gấp đôi số lượng key để đảm bảo an toàn
    max_retries = len(API_KEYS) * 2

    for attempt in range(max_retries):
        try:
            # Gán key hiện hành vào tham số gọi API
            kwargs["api_key"] = API_KEYS[current_key_idx]

            # Gọi hàm gốc của LightRAG
            result = await ollama_model_complete(
                prompt,
                system_prompt=system_prompt,
                history_messages=history_messages,
                **kwargs
            )

            # --- TẠO QUÃNG NGHỈ (THROTTLE) ĐỂ TRÁNH BỊ RATE LIMIT ---
            # Random nghỉ từ 1 đến 3 giây giữa mỗi Request thành công
            await asyncio.sleep(random.uniform(10.0, 15.0))

            return result

        except Exception as e:
            error_str = str(e).lower()
            # Nếu bắt trúng các lỗi kiểu Rate Limit, 429, Quota Exceeded...
            if "limit" in error_str or "429" in error_str or "quota" in error_str or "too many requests" in error_str:
                print(f"[CẢNH BÁO] API Key {API_KEYS[current_key_idx][:10]}... bị sập (Rate Limit/Quota). Đang Switch sang Key mới...")
                # Đi tới Key tiếp theo trong mảng, nếu hết mảng thì quay về số 0
                current_key_idx = (current_key_idx + 1) % len(API_KEYS)
            else:
                # Nếu không phải lỗi Rate limit (ví dụ mất mạng) -> quăng lỗi liền để Fix
                raise e

    raise Exception("Thất bại! Đã thử đổi toàn bộ API Keys nhưng tất cả đều bị Limit/Quota.")

# Import các hàm khởi tạo embedding và graph tuỳ thuộc vào setup của dự án bạn
# Ví dụ: từ utils của LightRAG hoặc tự định nghĩa HuggingFace

async def build_macro_layer(rag, custom_entities_dict, custom_relations_dict):
    print("\n--- GIAI ĐOẠN 2: NẠP TẦNG VĨ MÔ (MACRO) ---")
    print("1. Nạp Entities/Relations Vĩ Mô vào VectorDB...")
    if custom_entities_dict:
        await rag.entities_vdb.upsert(custom_entities_dict)
    if custom_relations_dict:
        await rag.relationships_vdb.upsert(custom_relations_dict)

    print("2. Nạp Node/Edge Vĩ mô vào GraphDB (Neo4j/NetworkX)...")
    for ent in custom_entities_dict.values():
        await rag.chunk_entity_relation_graph.upsert_node(ent["entity_name"], ent)

    for rel in custom_relations_dict.values():
        await rag.chunk_entity_relation_graph.upsert_edge(rel["src_id"], rel["tgt_id"], rel)
    print("-> Hoàn tất nạp tầng vĩ mô.")

async def build_micro_layer(rag, custom_chunks_dict):
    print("\n--- GIAI ĐOẠN 3: NẠP TẦNG VI MÔ (MICRO) ---")
    print("3. Nạp Data Nguyên Bản vào Local Text Storage...")
    if custom_chunks_dict:
        await rag.text_chunks.upsert(custom_chunks_dict)

    print("4. Nạp Embeddings Data Nguyên Bản vào VectorDB...")
    if custom_chunks_dict:
        await rag.chunks_vdb.upsert(custom_chunks_dict)

    print("5. [TỐN TIỀN/TỐN THỜI GIAN NHẤT] Kích hoạt LLM Extraction theo lô BATCH...")
    # Hàm bí mật ép LLM tuân thủ Chunk_id của bạn trỏ vào Micro Entity.
    if custom_chunks_dict:
        import itertools
        BATCH_SIZE = 20 # Cứ gặm xong 20 Chunk thì đẩy thẳng lên Mây!

        # Cắt từ điển lớn thành danh sách chứa các lô nhỏ
        items = list(custom_chunks_dict.items())
        batches = [dict(items[i:i + BATCH_SIZE]) for i in range(0, len(items), BATCH_SIZE)]

        for idx, batch_dict in enumerate(batches):
            print(f"\n🚀 Đang cày Cuốc Lô thứ {idx + 1}/{len(batches)} (Mỗi lô {BATCH_SIZE} Chunks)...")

            # CHUẨN BỊ MÔI TRƯỜNG STATUS ĐỂ NÉ TÌNH TRẠNG LỖI NoneType Status Lock
            pipeline_status = {"history_messages": [], "request_pending": False, "latest_message": ""}
            pipeline_status_lock = asyncio.Lock()

            # 1. MỒI LLM EXTRACT (Lưu tạm trên RAM)
            chunk_results = await rag._process_extract_entities(
                batch_dict,
                pipeline_status=pipeline_status,
                pipeline_status_lock=pipeline_status_lock
            )

            # 2. XẢ TỪ RAM ĐẨY LÊN CLOUD NEO4J VÀ MILVUS (Tiến trình quyết định)
            print(f"⏳ Đang Trộn và Up Lô {idx + 1} lên Cloud Neo4j/Milvus để chốt sổ...")
            await merge_nodes_and_edges(
                chunk_results=chunk_results,
                knowledge_graph_inst=rag.chunk_entity_relation_graph,
                entity_vdb=rag.entities_vdb,
                relationships_vdb=rag.relationships_vdb,
                global_config=asdict(rag),
                full_entities_storage=rag.full_entities,
                full_relations_storage=rag.full_relations,
                doc_id=f"custom_import_batch_{idx}", # Nhãn giả định theo lô
                pipeline_status=pipeline_status,
                pipeline_status_lock=pipeline_status_lock,
                llm_response_cache=rag.llm_response_cache,
                entity_chunks_storage=rag.entity_chunks,
                relation_chunks_storage=rag.relation_chunks,
                current_file_number=1,
                total_files=1,
                file_path="/kaggle/working/custom_kg_full.json"
            )

    print("-> Hoàn tất rút trích & nạp tầng vi mô lên Cloud!")
async def main():
    # 1) Đọc dữ liệu JSON đã build trước đó
    json_path = "/kaggle/working/custom_kg_full.json"
    if not os.path.exists(json_path):
        print(f"Lỗi: Không tìm thấy file {json_path}. Vui lòng chạy bước build custom_kg trước.")
        return

    print(f"Đang tải dữ liệu từ {json_path}...")
    with open(json_path, "r", encoding="utf-8") as f:
        custom_kg = json.load(f)

    # 2) Chuẩn hóa entity/relationship/chunk theo contract của LightRAG
    custom_entities_dict = {
        ent["entity_name"]: {
            **ent,
            "entity_id": ent["entity_name"],
            "content": f"{ent['entity_name']}: {ent.get('description', '')}",
            "file_path": ent.get("file_path", "unknown_source"),
        }
        for ent in custom_kg.get("entities", [])
    }

    custom_relations_dict = {
        f"{rel['src_id']}-{rel['tgt_id']}": {
            **rel,
            "content": rel.get("description", ""),
            "file_path": rel.get("file_path", "unknown_source"),
        }
        for rel in custom_kg.get("relationships", [])
    }

    # Giữ file_path để hệ thống citation/reference hoạt động đúng nguồn
    custom_chunks_dict = {
        chunk["source_id"]: {
            "content": chunk.get("content", ""),
            "source_id": chunk["source_id"],
            "file_path": chunk.get("file_path", "unknown_source"),
            "full_doc_id": chunk.get("file_path", chunk["source_id"]),
            "chunk_order_index": chunk.get("chunk_order_index", 0),
        }
        for chunk in custom_kg.get("chunks", [])
        if chunk.get("source_id")
    }

    print(f"Loaded {len(custom_entities_dict)} macro entities")
    print(f"Loaded {len(custom_relations_dict)} macro relationships")
    print(f"Loaded {len(custom_chunks_dict)} text chunks")

    # 3) Khởi tạo LightRAG
    WORKING_DIR = "./target_db"
    if not os.path.exists(WORKING_DIR):
        os.mkdir(WORKING_DIR)

    rag = LightRAG(
        working_dir=WORKING_DIR,
        llm_model_max_async=1,
        vector_storage="MilvusVectorDBStorage",
        graph_storage="Neo4JStorage",
        llm_model_func=rotating_ollama_model_complete,
        llm_model_name="gpt-oss:120b-cloud",
        embedding_func=EmbeddingFunc(
            embedding_dim=768,
            max_token_size=256,
            func=custom_hf_embedding,
        ),
    )

    print("\nĐang khởi tạo các kết nối tới Milvus, Neo4j và KVs...")
    await rag.initialize_storages()

    print("\nBắt đầu Pipeline Data Ingestion...")
    await build_macro_layer(rag, custom_entities_dict, custom_relations_dict)
    await build_micro_layer(rag, custom_chunks_dict)

    print("\n🚀 HOÀN TẤT NHÚNG DỮ LIỆU THÀNH CÔNG VÀO LIGHTRAG!")

Đang khởi tạo mô hình HuggingFace Embedding...

/tmp/ipykernel_55/4085658107.py:18: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  hf_model = HuggingFaceEmbeddings(

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [ ]:
await main()

Đang tải dữ liệu từ /kaggle/working/custom_kg_full.json...
Loaded 83 macro entities
Loaded 115 macro relationships
Loaded 4527 text chunks

INFO: [] Process 55 KV load full_docs with 0 records
INFO: [] Process 55 KV load text_chunks with 0 records
INFO: [] Process 55 KV load full_entities with 0 records
INFO: [] Process 55 KV load full_relations with 0 records
INFO: [] Process 55 KV load entity_chunks with 0 records
INFO: [] Process 55 KV load relation_chunks with 0 records

Đang khởi tạo các kết nối tới Milvus, Neo4j và KVs...

INFO: [] VectorDB collection 'entities' exists check: False
INFO: [] Creating new collection: entities
INFO: Milvus index configured: type=AUTOINDEX, metric=COSINE, params={}
INFO: [] Created indexes for collection: entities
INFO: [] Successfully created Milvus collection: entities
INFO: [] Milvus collection 'entities' initialized successfully
INFO: [] VectorDB collection 'relationships' exists check: False
INFO: [] Creating new collection: relationships
INFO: Milvus index configured: type=AUTOINDEX, metric=COSINE, params={}
INFO: [] Created indexes for collection: relationships
INFO: [] Successfully created Milvus collection: relationships
INFO: [] Milvus collection 'relationships' initialized successfully
INFO: [] VectorDB collection 'chunks' exists check: False
INFO: [] Creating new collection: chunks
INFO: Milvus index configured: type=AUTOINDEX, metric=COSINE, params={}
INFO: [] Created indexes for collection: chunks
INFO: [] Successfully created Milvus collection: chunks
INFO: [] Milvus collection 'chunks' initialized successfully
INFO: [base] Database chunk-entity-relation at neo4j+s://dc053a4e.databases.neo4j.io not found. Try to create specified database.
WARNING: [base] This Neo4j instance does not support creating databases. Try to use Neo4j Desktop/Enterprise version or DozerDB instead. Fallback to use the default database.
INFO: [base] Connected to None at neo4j+s://dc053a4e.databases.neo4j.io
INFO: [base] Ensured B-Tree index on entity_id for base in None
INFO: [base] No existing index 'entity_id_fulltext_idx_base' found. Creating new index.
INFO: [base] Creating full-text index 'entity_id_fulltext_idx_base' with Chinese tokenizer support.
INFO: [base] Successfully created full-text index 'entity_id_fulltext_idx_base' with CJK analyzer.
INFO: [] Process 55 KV load llm_response_cache with 0 records
INFO: [] Process 55 doc status load doc_status with 0 records

Bắt đầu Pipeline Data Ingestion...

--- GIAI ĐOẠN 2: NẠP TẦNG VĨ MÔ (MACRO) ---
1. Nạp Entities/Relations Vĩ Mô vào VectorDB...

INFO: Embedding func: 8 new workers initialized (Timeouts: Func: 30s, Worker: 60s, Health Check: 75s)

2. Nạp Node/Edge Vĩ mô vào GraphDB (Neo4j/NetworkX)...
-> Hoàn tất nạp tầng vĩ mô.

--- GIAI ĐOẠN 3: NẠP TẦNG VI MÔ (MICRO) ---
3. Nạp Data Nguyên Bản vào Local Text Storage...
4. Nạp Embeddings Data Nguyên Bản vào VectorDB...

INFO: LLM func: 1 new workers initialized (Timeouts: Func: 180s, Worker: 360s, Health Check: 375s)

5. [TỐN TIỀN/TỐN THỜI GIAN NHẤT] Kích hoạt LLM Extraction theo lô BATCH...

🚀 Đang cày Cuốc Lô thứ 1/227 (Mỗi lô 20 Chunks)...

INFO:  == LLM cache == saving: default:extract:a67f9e648b5fb14147f1b48e6c54e89f
INFO:  == LLM cache == saving: default:extract:ea781087a369a424f97289eac91a5b04
INFO: Chunk 1 of 20 extracted 8 Ent + 11 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_1
INFO:  == LLM cache == saving: default:extract:e6148d5af3101f2e41e8cda571c10009
INFO:  == LLM cache == saving: default:extract:4ab55fe2239d98f0585fdb79682b9738
INFO: Chunk 2 of 20 extracted 24 Ent + 24 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_2
INFO:  == LLM cache == saving: default:extract:b70cfc5683b8611a287a4d55a2267747
INFO:  == LLM cache == saving: default:extract:b010b6509bcea208d0373476d769a49a
INFO: Chunk 3 of 20 extracted 17 Ent + 17 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_3
INFO:  == LLM cache == saving: default:extract:948190bca0718277a9e45c09da24502f
INFO:  == LLM cache == saving: default:extract:d4c7781c36922e322f6e50617d6f8904
INFO: Chunk 4 of 20 extracted 22 Ent + 22 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_4
INFO:  == LLM cache == saving: default:extract:04aeb32b4c023da3a484b67bdce059e2
INFO:  == LLM cache == saving: default:extract:0473bae58d767b69b37fe91fa2e7a3c2
INFO: Chunk 5 of 20 extracted 13 Ent + 16 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_5
INFO:  == LLM cache == saving: default:extract:0cf464714130770443ac5f480e6b94b9
INFO:  == LLM cache == saving: default:extract:39c8f2dbbb55f140547d65aceb1fb265
INFO: Chunk 6 of 20 extracted 20 Ent + 23 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_6
INFO:  == LLM cache == saving: default:extract:f0d3c0e0b04de820aa2e7282589f19d0
INFO:  == LLM cache == saving: default:extract:b74e27d032acf2da18624697ca20845c
INFO: Chunk 7 of 20 extracted 32 Ent + 29 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_7
INFO:  == LLM cache == saving: default:extract:b6c4fbf62ff5ec00b462906e9ebf5a9f
INFO:  == LLM cache == saving: default:extract:b82a5793e12e961b83ed8feeb45e5f77
INFO: Chunk 8 of 20 extracted 12 Ent + 11 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_8
INFO:  == LLM cache == saving: default:extract:a123d6fbb581ac28f37712b8ff8faa55
INFO:  == LLM cache == saving: default:extract:b89ad7efb9f3a7e0dcf43db428884bbc
INFO: Chunk 9 of 20 extracted 10 Ent + 10 Rel chunk_01/2016/TTLT-TANDTC-VKSNDTC-BTP_9
INFO:  == LLM cache == saving: default:extract:93d86e5685ac27da3a6d52257dd9b66b
INFO:  == LLM cache == saving: default:extract:92967bea1f91a0ef3f8b47a48fff591c
INFO: Chunk 10 of 20 extracted 8 Ent + 12 Rel chunk_01/2022/TT-BTP_1
INFO:  == LLM cache == saving: default:extract:1a00e384a9d01cd31cb860b57e4f8863
INFO:  == LLM cache == saving: default:extract:059028fc31d085cb212baa704cfb5bda
INFO: Chunk 11 of 20 extracted 9 Ent + 10 Rel chunk_01/2022/TT-BTP_2
INFO:  == LLM cache == saving: default:extract:324b4dc12302e04446be17934a6938f5
INFO:  == LLM cache == saving: default:extract:bdbcb2e54ddf1a1fbea46bbb914a9f2a
INFO: Chunk 12 of 20 extracted 23 Ent + 22 Rel chunk_01/2022/TT-BTP_3
INFO:  == LLM cache == saving: default:extract:ed0e2f429809bbe71d64291bbb10264e
INFO:  == LLM cache == saving: default:extract:f3012744154a00ab3c8fae0d8c68ffb0
INFO: Chunk 13 of 20 extracted 14 Ent + 17 Rel chunk_01/2022/TT-BTP_4
INFO:  == LLM cache == saving: default:extract:e11e11eef454ee06496f7c06695caaff
INFO:  == LLM cache == saving: default:extract:95962e1f0af4c04d1a9a1cdd85d7b171
INFO: Chunk 14 of 20 extracted 14 Ent + 13 Rel chunk_01/2022/TT-BTP_5
INFO:  == LLM cache == saving: default:extract:a771fda00f0b31a6d67f1adfd651502f
INFO:  == LLM cache == saving: default:extract:ee4b85ea9d1e0bf7bc8adeb9ffc0c7f3
INFO: Chunk 15 of 20 extracted 19 Ent + 19 Rel chunk_01/2022/TT-BTP_6
INFO:  == LLM cache == saving: default:extract:cf7d46a1219afbbd0be7e6d534a74ec2
INFO:  == LLM cache == saving: default:extract:175630661ae7463a5a8a73fe3c00dfd0
INFO: Chunk 16 of 20 extracted 9 Ent + 11 Rel chunk_01/2022/TT-BTP_7
INFO:  == LLM cache == saving: default:extract:f7c0f551d0e758be3b364cd3d2cf77d0
INFO:  == LLM cache == saving: default:extract:4cc3ff2bedd775037d512b6654a0f961
INFO: Chunk 17 of 20 extracted 13 Ent + 11 Rel chunk_01/2022/TT-BTP_8_s1
INFO:  == LLM cache == saving: default:extract:9fee531808c66dc437ab24d2dda03ad4
INFO:  == LLM cache == saving: default:extract:8cb8d75201028333621231088ecd1c60
INFO: Chunk 18 of 20 extracted 24 Ent + 22 Rel chunk_01/2022/TT-BTP_8_s2
INFO:  == LLM cache == saving: default:extract:1fc78541463fc0c919950ec07113b4b0
INFO:  == LLM cache == saving: default:extract:9dcbb1d0f73380f29dfff38c77a06f82
INFO: Chunk 19 of 20 extracted 11 Ent + 12 Rel chunk_01/2022/TT-BTP_8_s3
INFO:  == LLM cache == saving: default:extract:eb0817c9248e0744fbdea68d21377759
INFO:  == LLM cache == saving: default:extract:da5569ea604f24cdff0829f009e7c445
INFO: Chunk 20 of 20 extracted 16 Ent + 14 Rel chunk_01/2022/TT-BTP_8_s4
INFO: Merging stage 1/1: /kaggle/working/custom_kg_full.json
INFO: Phase 1: Processing 251 entities from custom_import_batch_0 (async: 2)

⏳ Đang Trộn và Up Lô 1 lên Cloud Neo4j/Milvus để chốt sổ...

INFO: Merged: `01/2016/TTLT-TANDTC-VKSNDTC-BTP` | 1+4
INFO: Merged: `01/2022/TT-BTP` | 1+2
INFO: Phase 2: Processing 317 relations from custom_import_batch_0 (async: 2)
INFO: Phase 3: Updating final 251(251+0) entities and  317 relations from custom_import_batch_0
INFO: Completed merging: 251 entities, 0 extra entities, 317 relations

🚀 Đang cày Cuốc Lô thứ 2/227 (Mỗi lô 20 Chunks)...

INFO:  == LLM cache == saving: default:extract:0c44d26ba59224be3168eb0f83d9d454
INFO:  == LLM cache == saving: default:extract:3920dd1bee80b9a90b89933557c3c092
INFO: Chunk 1 of 20 extracted 9 Ent + 9 Rel chunk_01/2022/TT-BTP_8_s5
INFO:  == LLM cache == saving: default:extract:aa11c49f4cb81481c8d07a6f5278e6e7
INFO:  == LLM cache == saving: default:extract:1d7fdfd111389cde9866bcbef5d3e812
INFO: Chunk 2 of 20 extracted 11 Ent + 14 Rel chunk_01/2022/TT-BTP_9
INFO:  == LLM cache == saving: default:extract:6b95fd7e062cd0f8531f33ff36d9ecf9
INFO:  == LLM cache == saving: default:extract:adf8578589aea4da3dd6ec53572201ab
INFO: Chunk 3 of 20 extracted 14 Ent + 13 Rel chunk_01/2022/TT-BTP_10
INFO:  == LLM cache == saving: default:extract:bb89982df691fd7477191d5d6af48dc8
INFO:  == LLM cache == saving: default:extract:8fec0708e4ff144fb337138a4cd618b6
INFO: Chunk 4 of 20 extracted 17 Ent + 20 Rel chunk_01/2022/TT-BTP_11
INFO:  == LLM cache == saving: default:extract:9c8edca440352e857c346a7e0b8a2d6f
INFO:  == LLM cache == saving: default:extract:31117b3aaf83eb10535bd4641567430d
INFO: Chunk 5 of 20 extracted 15 Ent + 17 Rel chunk_01/2022/TT-BTP_12
INFO:  == LLM cache == saving: default:extract:0f1f2cab24b8194c95b70d0966cf1e5d
INFO:  == LLM cache == saving: default:extract:83e66a50ca0d6b715c8535e87a0da02a
INFO: Chunk 6 of 20 extracted 18 Ent + 19 Rel chunk_01/2022/TT-BTP_13
INFO:  == LLM cache == saving: default:extract:8258d5ce4d8c0551695203e21a4c039f
INFO:  == LLM cache == saving: default:extract:7f54d2303238f5f032edbdc7a366d68a
INFO: Chunk 7 of 20 extracted 13 Ent + 12 Rel chunk_01/2022/TT-BTP_14
INFO:  == LLM cache == saving: default:extract:1d60d161c66a9964136c148e45d76a71
INFO:  == LLM cache == saving: default:extract:7c3e295f40c213a6d84b71e1837adaba
INFO: Chunk 8 of 20 extracted 7 Ent + 6 Rel chunk_01/2022/TT-BTP_15
INFO:  == LLM cache == saving: default:extract:383f7c47fe82202e9b0f5747d7c725f4
INFO:  == LLM cache == saving: default:extract:c4ee5031a705b3efa4bedfdd900c5953
INFO: Chunk 9 of 20 extracted 6 Ent + 7 Rel chunk_01/2024/NQ-HĐTP_1
INFO:  == LLM cache == saving: default:extract:9fdd56b81f928c7430a77910e245c4b6
INFO:  == LLM cache == saving: default:extract:7eb14e83a7b0f15b1bce65ecd3a53330
INFO: Chunk 10 of 20 extracted 15 Ent + 12 Rel chunk_01/2024/NQ-HĐTP_2
INFO:  == LLM cache == saving: default:extract:6bf46fe8b7c4e82c70dddd18fe2d1870
INFO:  == LLM cache == saving: default:extract:12256fa5946f857d0efc1ff7acc35a38
INFO: Chunk 11 of 20 extracted 12 Ent + 14 Rel chunk_01/2024/NQ-HĐTP_3
INFO:  == LLM cache == saving: default:extract:fd6ed8c5aaeb49d4d5646eb77c36ac61
INFO:  == LLM cache == saving: default:extract:72eee56d8150f3743530430b051b361b
INFO: Chunk 12 of 20 extracted 13 Ent + 13 Rel chunk_01/2024/NQ-HĐTP_4
INFO:  == LLM cache == saving: default:extract:5c01783559640262fb64a9c9d3581953
INFO:  == LLM cache == saving: default:extract:e7b22a588a869d0e756a03d2800ab74d
INFO: Chunk 13 of 20 extracted 18 Ent + 22 Rel chunk_01/2024/NQ-HĐTP_5
INFO:  == LLM cache == saving: default:extract:73c9ec33e0a3995d49c149ede0c30f5b
INFO:  == LLM cache == saving: default:extract:905f8eae6da8261c3837bafc6a0dc61e
INFO: Chunk 14 of 20 extracted 15 Ent + 19 Rel chunk_01/2024/NQ-HĐTP_6
INFO:  == LLM cache == saving: default:extract:e3aa2cb000b68a2f5a10d1f78b1dc16b
INFO:  == LLM cache == saving: default:extract:686bff635b827a3e282d20e8755bc8f3
INFO: Chunk 15 of 20 extracted 21 Ent + 19 Rel chunk_01/2024/NQ-HĐTP_7
INFO:  == LLM cache == saving: default:extract:701be76601c7a5b61c5db3d44ef51b88
INFO:  == LLM cache == saving: default:extract:11abf36e3aca2063a26bac6ed99f44de
INFO: Chunk 16 of 20 extracted 33 Ent + 30 Rel chunk_01/2024/NQ-HĐTP_8
INFO:  == LLM cache == saving: default:extract:4fbecbcaf9e31c9355fdb028d62740c6
INFO:  == LLM cache == saving: default:extract:02db52ea105b018f4fe271a59a75f2fe
INFO: Chunk 17 of 20 extracted 23 Ent + 17 Rel chunk_01/2024/NQ-HĐTP_9
INFO:  == LLM cache == saving: default:extract:be0545e3edb3d0d20d339012f423d67f
INFO:  == LLM cache == saving: default:extract:1a6bbfa2a2f398fecaaa5114296f324f
INFO: Chunk 18 of 20 extracted 18 Ent + 19 Rel chunk_01/2024/NQ-HĐTP_10
INFO:  == LLM cache == saving: default:extract:ff74ed2b615162b2221bb6784d7632b9
INFO:  == LLM cache == saving: default:extract:cb0dc1f39b70cbb3b503a98f40322e13
INFO: Chunk 19 of 20 extracted 16 Ent + 16 Rel chunk_01/2024/NQ-HĐTP_11
INFO:  == LLM cache == saving: default:extract:c00fcbe1156af3312e4253eb288c34c3
INFO:  == LLM cache == saving: default:extract:fe5ba47062d9b82019ecf782cb64027a
INFO: Chunk 20 of 20 extracted 7 Ent + 7 Rel chunk_01/2024/NQ-HĐTP_12
INFO: Merging stage 1/1: /kaggle/working/custom_kg_full.json
INFO: Phase 1: Processing 259 entities from custom_import_batch_1 (async: 2)

⏳ Đang Trộn và Up Lô 2 lên Cloud Neo4j/Milvus để chốt sổ...

INFO: Merged: `Sổ hộ tịch` | 1+1
INFO: Merged: `Thông tin hộ tịch` | 1+1
INFO: Merged: `Điều 10` | 2+2
INFO: Merged: `Court` | 1+1
INFO: Merged: `Article 5` | 1+1
INFO: Merged: `Điều 9` | 3+1
INFO: Merged: `Civil Registry Officer` | 1+1
INFO: Merged: `Electronic Civil Registry Database` | 1+1
INFO: Merged: `Personal Identification Number` | 1+1
INFO: Merged: `National Population Database` | 1+1
INFO: Merged: `01/2022/TT-BTP` | 3+2
INFO:  == LLM cache == saving: default:summary:da737e90a9977c22ca6abae5e8fb9a42
WARNING: Summary tokens(296) exceeds embedding_token_limit(256)  for Entity: Điều 8
INFO: LLMmrg: `Điều 8` | 7+2
INFO:  == LLM cache == saving: default:summary:bcfbc74e7de7813dbecd5c5a72044f2b
WARNING: Summary tokens(278) exceeds embedding_token_limit(256)  for Entity: Luật Hôn Nhân Và Gia Đình
INFO: LLMmrg: `Luật Hôn Nhân Và Gia Đình` | 4+5
INFO: Merged: `Con` | 1+4
INFO:  == LLM cache == saving: default:summary:9ed4a3995efafa5a9164b9aab97d9acc
INFO: LLMmrg: `Tòa Án` | 3+6
INFO: Merged: `Điều 7` | 1+1
INFO: Merged: `Con Chưa Thành Niên` | 1+2
INFO: Merged: `Công Dân Việt Nam` | 1+1
INFO: Merged: `Phần Mềm Đăng Ký, Quản Lý Hộ Tịch Điện Tử Dùng Chung` | 1+3
INFO: Merged: `Sổ Hộ Tịch` | 3+2
INFO: Merged: `Cơ Quan Nhà Nước Có Thẩm Quyền` | 1+2
INFO:  == LLM cache == saving: default:summary:ec686888c9d8870e1ff585507aa6ffe9
INFO: LLMmrg: `Cơ Sở Dữ Liệu Hộ Tịch Điện Tử` | 7+3
INFO: Merged: `Hồ Sơ Đăng Ký Hộ Tịch` | 1+1
INFO: Merged: `Điều 12` | 2+1
INFO: Merged: `Tòa án` | 3+1
INFO: Merged: `Điều 13` | 1+1
INFO: Merged: `Bản Án` | 2+2
INFO: Merged: `Quyết Định` | 1+2
INFO: Merged: `Cơ Quan Đăng Ký Hộ Tịch` | 4+2
INFO: Merged: `Văn Bản Xác Nhận Thông Tin Hộ Tịch` | 2+1
INFO: Merged: `Cơ Quan Quản Lý Cơ Sở Dữ Liệu Hộ Tịch Điện Tử` | 1+1
INFO: Merged: `Nghị Định Số 87/2020/NĐ-CP` | 3+1
INFO: Merged: `Cơ Sở Dữ Liệu Quốc Gia Về Dân Cư` | 3+1
INFO: Merged: `Bộ Tư Pháp` | 3+1
INFO: Merged: `Ủy Ban Nhân Dân` | 1+1
INFO: Merged: `01/2024/NQ-HĐTP` | 1+3
INFO: Merged: `Điều 11` | 5+1
INFO: Merged: `Vợ` | 1+1
INFO: Merged: `Chồng` | 1+1
INFO: Merged: `Điều 2` | 1+1
INFO: Merged: `Tòa Án Nhân Dân Tối Cao` | 1+1
INFO: Merged: `Điều 3` | 2+2
INFO: Merged: `Vợ Chồng` | 1+1
INFO: Merged: `Điều 4` | 3+1
INFO: Phase 2: Processing 298 relations from custom_import_batch_1 (async: 2)
INFO: Chunks appended from relation: `Cơ Quan Quản Lý Cơ Sở Dữ Liệu Hộ Tịch Điện Tử`
INFO: Merged: `Cơ Quan Đăng Ký Hộ Tịch`~`Cơ Sở Dữ Liệu Hộ Tịch Điện Tử` | 1+2
INFO: Merged: `Cơ Sở Dữ Liệu Hộ Tịch Điện Tử`~`Văn Bản Xác Nhận Thông Tin Hộ Tịch` | 1+1
INFO: Merged: `Cơ Quan Quản Lý Cơ Sở Dữ Liệu Hộ Tịch Điện Tử`~`Cơ Sở Dữ Liệu Hộ Tịch Điện Tử` | 1+1
INFO: Merged: `Cơ Sở Dữ Liệu Hộ Tịch Điện Tử`~`Cơ Sở Dữ Liệu Quốc Gia Về Dân Cư` | 3+1
INFO: Merged: `Tòa Án`~`Vợ Chồng` | 1+1
INFO: Phase 3: Updating final 260(259+1) entities and  298 relations from custom_import_batch_1
INFO: Completed merging: 259 entities, 1 extra entities, 298 relations

🚀 Đang cày Cuốc Lô thứ 3/227 (Mỗi lô 20 Chunks)...

INFO:  == LLM cache == saving: default:extract:7a271f48cd006a5afd142c86e0330c30
INFO:  == LLM cache == saving: default:extract:d611342d89467c035a60fff0e732b8c4
INFO: Chunk 2 of 20 extracted 9 Ent + 9 Rel chunk_01/2025/TT-BTP_2
INFO:  == LLM cache == saving: default:extract:e41120dcd92ca59abe407c647a12fe7a
INFO:  == LLM cache == saving: default:extract:86b2804c84b47fd5b3cde0db67dd21f2
INFO: Chunk 3 of 20 extracted 34 Ent + 29 Rel chunk_01/2025/TT-BTP_3
INFO:  == LLM cache == saving: default:extract:89947334c1c40cbb3955fb7479382396
INFO:  == LLM cache == saving: default:extract:62b6c5093433fcaa8fb8dce23ef0d673
INFO: Chunk 4 of 20 extracted 12 Ent + 11 Rel chunk_02a/2015/TT-BTP_1
INFO:  == LLM cache == saving: default:extract:6e5000c8ce76c9431391b1d42dd60950
INFO:  == LLM cache == saving: default:extract:a0800ad47c0d6e857bd5ade385aceda9
INFO: Chunk 5 of 20 extracted 13 Ent + 14 Rel chunk_02a/2015/TT-BTP_2
INFO:  == LLM cache == saving: default:extract:bff489478fb4bb31b2e141f5ea258553
INFO:  == LLM cache == saving: default:extract:e2f9a021989bb76ad25a0573e9a2aa2d
INFO: Chunk 6 of 20 extracted 21 Ent + 18 Rel chunk_02a/2015/TT-BTP_3
INFO:  == LLM cache == saving: default:extract:dce13d89f3bcb19d29a4ddf8c889d7b8
INFO:  == LLM cache == saving: default:extract:607dfe24a7f9eb1a623d1b6c2854e92b
INFO: Chunk 7 of 20 extracted 13 Ent + 14 Rel chunk_02a/2015/TT-BTP_4
INFO:  == LLM cache == saving: default:extract:b116f9bc6c2c506ceffe9c9319e5fc48
INFO:  == LLM cache == saving: default:extract:29f627eb34c8e1e62edcd107d8f1b036
INFO: Chunk 8 of 20 extracted 21 Ent + 11 Rel chunk_02a/2015/TT-BTP_5